main/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin/edit'

  get 'gti619/home'

  get 'gti619/circle'

  get 'gti619/square'

  get 'gti619/admin_Panel'

  devise_for :users, :path_prefix => 'd' # routes for devise modules on User
  resources :users do
    post :unlock, :on => :member
	    get :unlock, :on => :member
		post :unlock, :on => :member
  end	# custom admin-type CRUD for users

  root 'gti619#home'

end

main/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable
		 
	
	
	# in User
ROLES = %w[gen_admin teacher_admin student]
def role?(base_role)
  ROLES.index(base_role.to_s) <= ROLES.index(role)
end
end

main/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	  @users = User.all

  end
	  def unlock
		user = User.find(params[:id])
		user.unlock_access!
	  end
  def edit
  end
end

main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up)        << :role
   devise_parameter_sanitizer.for(:account_update) << :role
  end
end

main/app/controllers/gti619_controller.rb
class Gti619Controller < ApplicationController
  def home

  end

  def circle

  end

  def square

  end

  def admin_Panel


  end
end

main/app/helpers/admin_helper.rb
module AdminHelper
end

main/app/helpers/application_helper.rb
module ApplicationHelper
end

main/app/helpers/gti619_helper.rb
module Gti619Helper
end

main/app/views/admin/edit.html.erb
<h1>Admin#edit</h1>
<p>Find me in app/views/admin/edit.html.erb</p>

main/app/views/admin/index.html.erb
					<% if user_signed_in? %>
<h1>Admin#index</h1>
<h1>Listing Users</h1>

<table class="table">
  <tr>
    <th>Email</th>
    <th>Last connection</th>
    <th>Locked At</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.last_sign_in_at %></td>
	  <td><%= user.locked_at %></td>
	  <td><%= link_to(t('common.unlock'), unlock_user_path(user), method: :post, class: 'button-xs') unless user == current_user %></td>
    </tr>
    <% end %>
</table>
<% else %>
												Please login again
						<% end %>

main/app/views/gti619/admin_Panel.html.erb
					<% if user_signed_in? %>
<h1>Gti619#admin_Panel</h1>
						<% else %>
												Please login again
						<% end %>

main/app/views/gti619/circle.html.erb
					<% if user_signed_in? %>
<h1 class="animated fadeInDown"data-id='1'>Gti619#circle</h1>
<div class="circle animated growIn" data-id='2'></div>
						<% else %>
												Please login again
						<% end %>

main/app/views/gti619/home.html.erb
<h1>Gti619#home</h1>
<p>Find me in app/views/gti619/home.html.erb</p>

main/app/views/gti619/square.html.erb
					<% if user_signed_in? %>
<h1 class="animated fadeInDown"data-id='1'>Gti619#square</h1>
<div class="square animated growIn" data-id='2'></div>
						<% else %>
						Please login again
						<% end %>

main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Main</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="http://www.expertus.ca/sandbox/wp-content/themes/expertus/css/animations.css">
  <script type="text/javascript" src="http://www.expertus.ca/wp-content/themes/expertus/js/jquery-1.9.1.min.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
	<style>
		.nav{
			width: 100%;
			background-color: gray;
		}
		.nav > li{
			float: left;
			padding: 15px;
			list-style-type: none;
			-webkit-transition: background-color 0.5s ease-out; */
			-moz-transition: background-color 0.5s ease-out;
			-o-transition: background-color 0.5s ease-out;
			transition: background-color 0.5s ease-out;
		}
		.nav > li:hover{
			background-color: white;
		}
		.nav > li > a{
			color: white;
			text-decoration: none;
			-webkit-transition: color 0.5s ease-out; */
			-moz-transition: color 0.5s ease-out;
			-o-transition: color 0.5s ease-out;
			transition: color 0.5s ease-out;
		}
		.nav > li:hover > a{
			color: gray;
		}
		.myBody{
			margin: 0;
			position: absolute;
			top: -16px;
			width: 100%;
		}
		.main-container{
			text-align: center;
			margin: 0 auto;
			padding-top: 10%;
		}
		.flash{
		  text-align: center;
		}
		.square{
			width: 100px;
			height: 100px;
			background: gray;
			margin: 0 auto;
		}
		.circle{
			width: 100px;
			height: 100px;
			background: gray;
			-moz-border-radius: 50px;
			-webkit-border-radius: 50px;
			border-radius: 50%;
			margin: 0 auto;
		}
		.table{
			margin: 0 auto;
		}
		.table > tbody{
			text-align: left;
		}

	</style>
</head>
<body class="myBody">
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<nav>
				<ul class="nav">
					<li><%= link_to "Home", root_path %></li>

					<% if user_signed_in? %>
						<% if current_user.role == "cercle" || current_user.role == "admin" %>
							<li><%= link_to "Cercle", gti619_circle_path %></li>
						<% end %>
						<% if current_user.role == "carre" || current_user.role == "admin" %>
							<li><%= link_to "Carre", gti619_square_path %></li>
						<% end %>
						<% if current_user.role == "admin" %>
							<li><%= link_to "Admin Panel", admin_index_path %></li>
						<% end %>
						<li><%= link_to "Change your password", edit_user_registration_path %></li>
						<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
		
					<% else %>
						<li><%= link_to "Login", new_user_session_path %></li>
					<% end %>
					<div style="clear: both;"
				</ul>
			</nav>
		</div>
	</header>
	<div class="main-container animatedParent" data-sequence='1000'>
		<%= yield %>
	</div>
	<% flash.each do |key, value| %>
	  <div class="flash <%= key %>"><%= value %></div>
	<% end %>
<script src="http://www.expertus.ca/sandbox/wp-content/themes/expertus/js/css3-animate-it.js"></script>
</body>
</html>